### ISSUE TITLE
Support scraping multiple FHIR servers

### ISSUE THREAD

**Issue by chgl** [chgl/fhir-server-exporter#56]
Maybe configurable like this:

```yaml
servers:
  - name: test-fhir
    url: http://example.com/fhir
    interval: 60s # scrape every 60s
    auth:
      basic:
        username: user
        password: password
  - name: hapi-base
    url: https://hapi.fhir.org/baseR4
    interval: 10min # scrape every 10 minutes
```

Each server name is added as a label to `fhir_resource_count`:

```console
fhir_resource_count{server="test-fhir", type="Patient"} 124005
fhir_resource_count{server="hapi-base", type="Patient"} 124006
```
